import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

interface PlanTable {
  title: string;
  rows: Array<{
    columns: string[];
  }>;
}

interface Plan {
  title: string;
  prompt: string;
  tables: PlanTable[];
  startDate?: string | null;
  endDate?: string | null;
}

// Extend jsPDF type to include lastAutoTable
declare module 'jspdf' {
  interface jsPDF {
    lastAutoTable: {
      finalY: number;
    };
  }
}

export const exportPlanToPDF = (plan: Plan) => {
  const doc = new jsPDF();
  
  // Add title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(plan.title, 14, 20);
  
  // Add prompt/description
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const promptLines = doc.splitTextToSize(plan.prompt, 180);
  doc.text(promptLines, 14, 30);
  
  let yPosition = 30 + (promptLines.length * 5) + 10;
  
  // Add dates if available
  if (plan.startDate && plan.endDate) {
    doc.setFontSize(9);
    doc.setTextColor(100);
    const startDate = new Date(plan.startDate).toLocaleDateString();
    const endDate = new Date(plan.endDate).toLocaleDateString();
    doc.text(`Duration: ${startDate} - ${endDate}`, 14, yPosition);
    yPosition += 10;
  }
  
  // Add each table
  plan.tables.forEach((table, tableIndex) => {
    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }
    
    // Add table title
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text(table.title, 14, yPosition);
    yPosition += 8;
    
    // Prepare table data
    const tableData = table.rows.map(row => row.columns);
    
    // Determine if this is a vertical table (first column as headers)
    const isVerticalTable = tableData.length > 0 && tableData[0].length <= 2;
    
    if (isVerticalTable) {
      // Vertical table: first column is headers, second is values
      autoTable(doc, {
        startY: yPosition,
        head: [],
        body: tableData,
        theme: 'grid',
        styles: {
          fontSize: 9,
          cellPadding: 3,
        },
        columnStyles: {
          0: { fontStyle: 'bold', fillColor: [240, 240, 240] },
        },
        margin: { left: 14 },
      });
    } else {
      // Horizontal table: first row as headers
      const headers = tableData.length > 0 ? [tableData[0]] : [];
      const body = tableData.slice(1);
      
      autoTable(doc, {
        startY: yPosition,
        head: headers,
        body: body,
        theme: 'grid',
        styles: {
          fontSize: 9,
          cellPadding: 3,
        },
        headStyles: {
          fillColor: [54, 89, 184],
          textColor: 255,
          fontStyle: 'bold',
        },
        margin: { left: 14 },
      });
    }
    
    // Update yPosition for next table
    yPosition = doc.lastAutoTable.finalY + 15;
  });
  
  // Add footer with generation date
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by Synapse - ${new Date().toLocaleDateString()}`,
      14,
      doc.internal.pageSize.height - 10
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width - 30,
      doc.internal.pageSize.height - 10
    );
  }
  
  // Save the PDF
  const fileName = `${plan.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`;
  doc.save(fileName);
};
