import type { Metadata } from 'next';
import './globals.css';
import { StoreProvider } from '@/lib/redux/StoreProvider';
import Providers from './providers';
import UserProfile from '@/components/UserProfile';

export const metadata: Metadata = {
  title: 'Synapse',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Providers>
          <StoreProvider>
            <UserProfile />
            {children}
          </StoreProvider>
        </Providers>
      </body>
    </html>
  );
}
