import type { Metadata } from 'next';
import './globals.css';
import { StoreProvider } from '@/lib/redux/StoreProvider';
import Providers from './providers';
import Sidebar from '@/components/Sidebar';
import { Hanalei_Fill } from "next/font/google";

const hanaleiFill = Hanalei_Fill({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-hanalei-fill",
});

export const metadata: Metadata = {
  title: 'Synapse',
  description: 'Generated by create next ap',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={hanaleiFill.variable}>
      <body
        className={`antialiased`}
      >
        <Providers>
          <StoreProvider>
            <Sidebar />
            {children}
          </StoreProvider>
        </Providers>
      </body>
    </html>
  );
}
